mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
useLocalRepo=false
genTR=false

# versions
version=7.9.0-SNAPSHOT
mc_version=7.9.0-SNAPSHOT
se_commons_version =7.9.0-SNAPSHOT

junit_version=5.14.1
junit_platform_version=1.14.1
guava_version=33.5.0-jre
