/* generated from model null*/
/* generated by template symboltable.ModelNameCalculator*/

package automaton._symboltable;

import java.util.Collections;
import java.util.Set;

import com.google.common.collect.ImmutableSet;
import de.se_rwth.commons.Names;

public class AutomatonModelNameCalculator extends AutomatonModelNameCalculatorTOP {

  @Override
  protected Set<String> calculateModelNameForState(String name) {
    // e.g., if p.Automaton.State, return p.Automaton
    if (!Names.getQualifier(name).isEmpty()) {
      return ImmutableSet.of(Names.getQualifier(name));
    }

    return Collections.emptySet();
  }
}
